language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
<<<<<<< HEAD
<<<<<<< HEAD
  - mysql -e 'CREATE DATABASE smoi_db;'
=======
  - mysql -e 'CREATE DATABASE testdb;'
>>>>>>> 75103b7c01413296496432350145041a580ff022
=======

  - mysql -e 'CREATE DATABASE smoi_db;'
>>>>>>> 9256c7f439d4d1b51a22247d2e68ed5fbb871186
